name: Build and Package PDF Converter App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Package the app
        run: npm run dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@3c9461b95db90d7ed5a58f0f02d1e6fe114d8f1a
        with:
          name: electron-app
          path: dist/

      - name: Debugging
        run: |
          echo "List all files in the current directory"
          ls -al
